
package com.mycompany.biblioSystem.vista;

import com.mycompany.biblioSystem.controlador.*;
import java.awt.Image;
import javax.swing.ImageIcon;

public class editarLibro extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(editarLibro.class.getName());
    private SistemaLibros sistema;
    private String codigoOriginal;
    /**
     * Creates new form editarLibro
     */
    public editarLibro(java.awt.Frame parent, boolean modal, SistemaLibros sistema, String cambio) {
        super(parent, modal);
        this.sistema = sistema;
        this.codigoOriginal = cambio;
        initComponents();
        Image icono = new ImageIcon(getClass().getResource("/imagenes/icon.jpeg")).getImage();
        setIconImage(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        generoTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        anioTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        isbnTxt = new javax.swing.JTextField();
        disponiblesTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        tituloTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        autorTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Genero");

        jLabel1.setText("Codigo");

        jLabel6.setText("Año");

        jLabel2.setText("ISBN");

        jLabel7.setText("Disponibles");

        disponiblesTxt.addActionListener(this::disponiblesTxtActionPerformed);

        jLabel3.setText("Título");

        confirmButton.setText("jButton1");
        confirmButton.addActionListener(this::confirmButtonActionPerformed);

        jLabel4.setText("Autor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(codigoTxt)
                        .addComponent(isbnTxt)
                        .addComponent(jLabel3)
                        .addComponent(tituloTxt)
                        .addComponent(jLabel4)
                        .addComponent(autorTxt)
                        .addComponent(jLabel5)
                        .addComponent(generoTxt)
                        .addComponent(jLabel6)
                        .addComponent(anioTxt)
                        .addComponent(jLabel7)
                        .addComponent(disponiblesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                    .addComponent(confirmButton))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isbnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disponiblesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disponiblesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disponiblesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disponiblesTxtActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        String codigo = codigoTxt.getText();
       String ISBN = isbnTxt.getText();
       String titulo = (tituloTxt.getText());
       String autor = autorTxt.getText();
       String genero = generoTxt.getText();
       String anio = (anioTxt.getText());
       int disponibles = Integer.parseInt((disponiblesTxt.getText()));
       if(!codigo.isEmpty() && !ISBN.isEmpty() && !titulo.isEmpty() && !autor.isEmpty() && 
           !genero.isEmpty() && !anio.isEmpty()){
       if(sistema.revisarLibros(codigo, ISBN) == false){
       sistema.editarLibro(codigoOriginal, codigo, ISBN, titulo, autor, genero, anio, disponibles);
       dispose();
       }
       else{String error = "Error1: el codigo o ISBN ya esta registrado";
            Error dialog = new Error(null, true, error);
            dialog.setVisible(true);}
       }else{String error = "Error6: Campos incompletos";
            Error dialog = new Error(null, true, error);
            dialog.setVisible(true);}
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anioTxt;
    private javax.swing.JTextField autorTxt;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField disponiblesTxt;
    private javax.swing.JTextField generoTxt;
    private javax.swing.JTextField isbnTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tituloTxt;
    // End of variables declaration//GEN-END:variables
}
