
package com.mycompany.biblioSystem.vista;
import com.mycompany.biblioSystem.controlador.*;
import com.mycompany.biblioSystem.modelo.*;
import javax.swing.table.DefaultTableModel;


public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());
    private SistemaUsuarios sistema;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(SistemaUsuarios sistema) {
        initComponents();
        Operador dialog = new Operador(this, true, sistema);
        this.sistema = sistema;
        cargarTablaOperadores();
    }

    public void cargarTablaOperadores() {
   DefaultTableModel modelo = (DefaultTableModel) tablaOperadores.getModel();
   modelo.setRowCount(0);
   Usuario[] operadores = sistema.getOperadores();

    for (int i = 0; i < operadores.length; i++) {

        modelo.addRow(new Object[]{
            operadores[i].getId(),
            operadores[i].getNombre(),
            operadores[i].getPassword()
        });
}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        tipoSesion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tipoRol = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cantLibros = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cantUsuarios = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cantPrestamos = new javax.swing.JLabel();
        menu = new javax.swing.JTabbedPane();
        menuLibros = new javax.swing.JScrollPane();
        modificarLibro = new javax.swing.JPanel();
        nuevoLibro = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        eliminarLibro = new javax.swing.JButton();
        buscarLibros = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        scrollLibros = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        menuUsuarios = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        nuevoUsuario = new javax.swing.JButton();
        modificarUsuario = new javax.swing.JButton();
        eliminarUsuario = new javax.swing.JButton();
        buscarUsuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        scrollUsuarios = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        menuPrestamos = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        nuevoPrestamo = new javax.swing.JButton();
        registrarPrestamo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tipoDevolucion = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        menuReportes = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tipoReporte = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        scrollReportes = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        nuevoOperador = new javax.swing.JButton();
        modificarOperador = new javax.swing.JButton();
        eliminarOperador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOperadores = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        edicion = new javax.swing.JMenu();
        ver = new javax.swing.JMenu();
        herramientas = new javax.swing.JMenu();
        ayuda = new javax.swing.JMenu();

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(678, 27));

        tipoSesion.setText("Sesion: Administrador del Sistema");

        jLabel2.setText("|");

        tipoRol.setText("Rol: Administrador");

        jLabel4.setText("|");

        cantLibros.setText("Libros: 100/100");

        jLabel6.setText("|");

        cantUsuarios.setText("Usuarios: 50/50");

        jLabel8.setText("|");

        cantPrestamos.setText("Prestamos activos: 200/200");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoRol, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantLibros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantPrestamos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipoSesion)
                    .addComponent(tipoRol)
                    .addComponent(jLabel4)
                    .addComponent(cantLibros)
                    .addComponent(jLabel6)
                    .addComponent(cantUsuarios)
                    .addComponent(jLabel8)
                    .addComponent(cantPrestamos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nuevoLibro.setText("Nuevo ");
        nuevoLibro.addActionListener(this::nuevoLibroActionPerformed);

        jButton1.setText("Modificar");

        eliminarLibro.setText("Eliminar");
        eliminarLibro.addActionListener(this::eliminarLibroActionPerformed);

        buscarLibros.setText("ISBN, TITUlo");
        buscarLibros.addActionListener(this::buscarLibrosActionPerformed);

        jLabel10.setText("Buscar :");

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "ISBN", "Título", "Autor", "Genero", "Año", "Disponibles"
            }
        ));
        scrollLibros.setViewportView(tablaLibros);

        javax.swing.GroupLayout modificarLibroLayout = new javax.swing.GroupLayout(modificarLibro);
        modificarLibro.setLayout(modificarLibroLayout);
        modificarLibroLayout.setHorizontalGroup(
            modificarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modificarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollLibros)
                    .addGroup(modificarLibroLayout.createSequentialGroup()
                        .addComponent(nuevoLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        modificarLibroLayout.setVerticalGroup(
            modificarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modificarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoLibro)
                    .addComponent(jButton1)
                    .addComponent(eliminarLibro)
                    .addComponent(buscarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuLibros.setViewportView(modificarLibro);

        menu.addTab("Libros ", menuLibros);

        nuevoUsuario.setText("Nuevo ");
        nuevoUsuario.addActionListener(this::nuevoUsuarioActionPerformed);

        modificarUsuario.setText("Modificar");
        modificarUsuario.addActionListener(this::modificarUsuarioActionPerformed);

        eliminarUsuario.setText("Eliminar");

        buscarUsuario.setText("jTextField2");

        jLabel11.setText("Buscar :");

        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Carné", "Nombre completo", "Carrera", "Correo electrónico"
            }
        ));
        scrollUsuarios.setViewportView(tableUsuarios);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollUsuarios)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nuevoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoUsuario)
                    .addComponent(modificarUsuario)
                    .addComponent(eliminarUsuario)
                    .addComponent(buscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuUsuarios.setViewportView(jPanel3);

        menu.addTab("Usuarios", menuUsuarios);

        nuevoPrestamo.setText("Nuevo prestamo");

        registrarPrestamo.setText("Registrar devolución");
        registrarPrestamo.addActionListener(this::registrarPrestamoActionPerformed);

        jLabel12.setText("Filtro:");

        tipoDevolucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipoDevolucion.addActionListener(this::tipoDevolucionActionPerformed);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Libro", "Fecha de prestamo", "Fecha de devolución", "Estado"
            }
        ));
        jScrollPane7.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nuevoPrestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registrarPrestamo)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 225, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoPrestamo)
                    .addComponent(registrarPrestamo)
                    .addComponent(jLabel12)
                    .addComponent(tipoDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuPrestamos.setViewportView(jPanel4);

        menu.addTab("Prestamos", menuPrestamos);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("Seleccione un reporte: ");

        jLabel14.setText("Reporte: ");

        tipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        jLabel15.setText("Libros o el reporte");

        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollReportes.setViewportView(tablaReportes);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuReportes.setViewportView(jPanel5);

        menu.addTab("Reportes", menuReportes);

        nuevoOperador.setText("Nuevo");
        nuevoOperador.addActionListener(this::nuevoOperadorActionPerformed);

        modificarOperador.setText("Modificar");

        eliminarOperador.setText("Eliminar");

        jLabel1.setText("Buscar:");

        jTextField1.setText("jTextField1");

        tablaOperadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaOperadores);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nuevoOperador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificarOperador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarOperador)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoOperador)
                    .addComponent(modificarOperador)
                    .addComponent(eliminarOperador)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.addTab("Operadores", jPanel2);

        jMenu1.setText("Archivo");
        menuBar.add(jMenu1);

        edicion.setText("Edición");
        menuBar.add(edicion);

        ver.setText("Ver");
        menuBar.add(ver);

        herramientas.setText("Herramientas");
        menuBar.add(herramientas);

        ayuda.setText("Ayuda");
        menuBar.add(ayuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
            .addComponent(menu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDevolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoDevolucionActionPerformed

    private void registrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarPrestamoActionPerformed

    private void modificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarUsuarioActionPerformed

    private void nuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoUsuarioActionPerformed

    private void buscarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarLibrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarLibrosActionPerformed

    private void eliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarLibroActionPerformed

    private void nuevoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoLibroActionPerformed

    private void nuevoOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoOperadorActionPerformed
        Operador dialog = new Operador(this, true, sistema); // 👈 pasas sistema
    dialog.setVisible(true);

    cargarTablaOperadores();
    }//GEN-LAST:event_nuevoOperadorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ayuda;
    private javax.swing.JTextField buscarLibros;
    private javax.swing.JTextField buscarUsuario;
    private javax.swing.JLabel cantLibros;
    private javax.swing.JLabel cantPrestamos;
    private javax.swing.JLabel cantUsuarios;
    private javax.swing.JMenu edicion;
    private javax.swing.JButton eliminarLibro;
    private javax.swing.JButton eliminarOperador;
    private javax.swing.JButton eliminarUsuario;
    private javax.swing.JMenu herramientas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JScrollPane menuLibros;
    private javax.swing.JScrollPane menuPrestamos;
    private javax.swing.JScrollPane menuReportes;
    private javax.swing.JScrollPane menuUsuarios;
    private javax.swing.JPanel modificarLibro;
    private javax.swing.JButton modificarOperador;
    private javax.swing.JButton modificarUsuario;
    private javax.swing.JToggleButton nuevoLibro;
    private javax.swing.JButton nuevoOperador;
    private javax.swing.JButton nuevoPrestamo;
    private javax.swing.JButton nuevoUsuario;
    private javax.swing.JButton registrarPrestamo;
    private javax.swing.JScrollPane scrollLibros;
    private javax.swing.JScrollPane scrollReportes;
    private javax.swing.JScrollPane scrollUsuarios;
    private javax.swing.JTable tablaLibros;
    private javax.swing.JTable tablaOperadores;
    private javax.swing.JTable tablaReportes;
    private javax.swing.JTable tableUsuarios;
    private javax.swing.JComboBox<String> tipoDevolucion;
    private javax.swing.JComboBox<String> tipoReporte;
    private javax.swing.JLabel tipoRol;
    private javax.swing.JLabel tipoSesion;
    private javax.swing.JMenu ver;
    // End of variables declaration//GEN-END:variables
}
