
package com.mycompany.biblioSystem.vista;
import com.mycompany.biblioSystem.controlador.*;
import com.mycompany.biblioSystem.modelo.*;

public class registroDevolucion extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(registroDevolucion.class.getName());
    private SistemaPrestamos sistema; 
    private String IdCambio;
    /**
     * Creates new form registroDevolucion
     */
    public registroDevolucion(java.awt.Frame parent, boolean modal, SistemaPrestamos sistema, String cambio) {
        super(parent, modal);
        this.sistema = sistema;
        this.IdCambio = cambio;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        opcionSi = new javax.swing.JButton();
        opcionNo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Registrar Devolucion");

        opcionSi.setText("Si");
        opcionSi.addActionListener(this::opcionSiActionPerformed);

        opcionNo.setText("No");
        opcionNo.addActionListener(this::opcionNoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opcionSi)
                        .addGap(18, 18, 18)
                        .addComponent(opcionNo))
                    .addComponent(jLabel1))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionSi)
                    .addComponent(opcionNo))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSiActionPerformed
        sistema.devolverLibro(IdCambio);
        dispose();
    }//GEN-LAST:event_opcionSiActionPerformed

    private void opcionNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionNoActionPerformed
        dispose();
    }//GEN-LAST:event_opcionNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton opcionNo;
    private javax.swing.JButton opcionSi;
    // End of variables declaration//GEN-END:variables
}
